package com.linc.network.model.stripe.intent

data class PaymentIntentApiModel(
    val amount: Int,
    val amount_capturable: Int,
    val amount_received: Int,
    val application: Any,
    val application_fee_amount: Any,
    val canceled_at: Any,
    val cancellation_reason: Any,
    val capture_method: String,
    val client_secret: String,
    val confirmation_method: String,
    val created: Int,
    val currency: String,
    val customer: String,
    val description: Any,
    val id: String,
    val invoice: Any,
    val last_payment_error: Any,
    val livemode: Boolean,
    val next_action: Any,
    val `object`: String,
    val on_behalf_of: Any,
    val payment_method: Any,
    val processing: Any,
    val receipt_email: Any,
    val review: Any,
    val setup_future_usage: Any,
    val shipping: Any,
    val source: Any,
    val statement_descriptor: Any,
    val statement_descriptor_suffix: Any,
    val status: String,
    val transfer_data: Any,
    val transfer_group: Any
)