package com.linc.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import com.linc.ui.resources.BookstoreStrings

val MaterialTheme.strings: LocalizedStrings
    @Composable
    @ReadOnlyComposable
    get() = LocalStringProvider.current

val MaterialTheme.strings2: BookstoreStrings
    @Composable
    @ReadOnlyComposable
    get() = LocalStringProvider2.current

val LocalStringProvider = staticCompositionLocalOf { englishLocaleStrings }
val LocalStringProvider2 = staticCompositionLocalOf { BookstoreStrings }

data class LocalizedStrings(
    val and: String,
    val andSpaced: String,
    val cancel: String,
    val pay: String,
    val addToCart: String,
    val makeOrder: String,
    val payWithPrice: String,
    val buyWithPrice: String,
    val ordersWithCount: String,
    val ratingWithCount: String,
    val purchaseAllOrders: String,
    val quantityLabel: String,
    val bookPriceLabel: String,
    val totalPriceLabel: String,
    val createOrder: String,
    val bookmarks: String,
    val interests: String,
    val aboutBook: String,
    val buyNow: String,
    val addToCartWithPrice: String,
    val goToCart: String,
    val payForOrder: String,
    val share: String,
    val books: String,
    val searchBooksHint: String,
    val seeAll: String,
    val notFound: String,
    val bookNotFound: String,
    val cart: String,
    val preferences: String,
    val language: String,
)

fun fromMap(strings: Map<String, String>) =     LocalizedStrings(
    and = strings["and"] ?: "and",
    andSpaced = strings["andSpaced"] ?: "andSpaced",
    cancel = strings["cancel"] ?: "cancel",
    pay = strings["pay"] ?: "pay",
    addToCart = strings["addToCart"] ?: "addToCart",
    makeOrder = strings["makeOrder"] ?: "makeOrder",
    payWithPrice = strings["payWithPrice"] ?: "payWithPrice",
    buyWithPrice = strings["buyWithPrice"] ?: "buyWithPrice",
    ordersWithCount = strings["ordersWithCount"] ?: "ordersWithCount",
    ratingWithCount = strings["ratingWithCount"] ?: "ratingWithCount",
    purchaseAllOrders = strings["purchaseAllOrders"] ?: "purchaseAllOrders",
    quantityLabel = strings["quantityLabel"] ?: "quantityLabel",
    bookPriceLabel = strings["bookPriceLabel"] ?: "bookPriceLabel",
    totalPriceLabel = strings["totalPriceLabel"] ?: "totalPriceLabel",
    createOrder = strings["createOrder"] ?: "createOrder",
    bookmarks = strings["bookmarks"] ?: "bookmarks",
    interests = strings["interests"] ?: "interests",
    aboutBook = strings["aboutBook"] ?: "aboutBook",
    buyNow = strings["buyNow"] ?: "buyNow",
    addToCartWithPrice = strings["addToCartWithPrice"] ?: "addToCartWithPrice",
    goToCart = strings["goToCart"] ?: "goToCart",
    payForOrder = strings["payForOrder"] ?: "payForOrder",
    share = strings["share"] ?: "share",
    books = strings["books"] ?: "books",
    searchBooksHint = strings["searchBooksHint"] ?: "searchBooksHint",
    seeAll = strings["seeAll"] ?: "seeAll",
    notFound = strings["notFound"] ?: "notFound",
    bookNotFound = strings["bookNotFound"] ?: "bookNotFound",
    cart = strings["cart"] ?: "cart",
    preferences = strings["preferences"] ?: "preferences",
    language = strings["language"] ?: "language"
)


val englishLocaleStrings = LocalizedStrings(
    and = "and",
    andSpaced = " and ",
    cancel = "Cancel",
    pay = "Pay",
    addToCart = "Add to cart",
    makeOrder = "Make order",
    payWithPrice = "Pay %s",
    buyWithPrice = "Buy (%s)",
    ordersWithCount = "Orders (%d)",
    ratingWithCount = "%.2f (%d)",
    purchaseAllOrders = "Purchase all",
    quantityLabel = "Quantity:",
    bookPriceLabel = "Book price:",
    totalPriceLabel = "Total price:",
    createOrder = "Create order",
    bookmarks = "Bookmarks",
    interests = "Interests",
    aboutBook = "About book",
    buyNow = "Buy now",
    addToCartWithPrice = "Add to cart (%s)",
    goToCart = "Go to cart",
    payForOrder = "Pay for order",
    share = "Share",
    books = "Books",
    searchBooksHint = "Search books by title, author, ISBN …",
    seeAll = "See all",
    notFound = "Not found!",
    bookNotFound = "Book not found!",
    cart = "Cart",
    preferences = "Preferences",
    language = "Language"
)

val ukrainianLocaleStrings = LocalizedStrings(
    and = "та",
    andSpaced = " та ",
    cancel = "Скасувати",
    pay = "Оплатити",
    addToCart = "Додати в кошик",
    makeOrder = "Зробити замовлення",
    payWithPrice = "Оплатити %s",
    buyWithPrice = "Купити (%s)",
    ordersWithCount = "Замовлення (%d)",
    ratingWithCount = "%.2f (%d)",
    purchaseAllOrders = "Купити все",
    quantityLabel = "Кількість:",
    bookPriceLabel = "Вартість книги:",
    totalPriceLabel = "Загальна вартість:",
    createOrder = "Створити замовлення",
    bookmarks = "Закладки",
    interests = "Інтереси",
    aboutBook = "Про книгу",
    buyNow = "Купити зараз",
    addToCartWithPrice = "Додати в кошик (%s)",
    goToCart = "Перейти до кошика",
    payForOrder = "Оплатити замовлення",
    share = "Поширити",
    books = "Книги",
    searchBooksHint = "Пошук книги за назвою, автором, ISBN …",
    seeAll = "Переглянути все",
    notFound = "Не знайдено!",
    bookNotFound = "Книгу не знайдено!",
    cart = "Кошик",
    preferences = "Уподобання",
    language = "Мова"
)

val polishLocaleStrings = LocalizedStrings(
    and = "a",
    andSpaced = " a ",
    cancel = "Anulować",
    pay = "Płacić",
    addToCart = "Dodaj do koszyka",
    makeOrder = "Złóż zamówienie",
    payWithPrice = "Płacić %s",
    buyWithPrice = "Kupić (%s)",
    ordersWithCount = "Zamówienia (%d)",
    ratingWithCount = "%.2f (%d)",
    purchaseAllOrders = "Kup wszystko",
    quantityLabel = "Ilość:",
    bookPriceLabel = "Cena książki:",
    totalPriceLabel = "Cena całkowita:",
    createOrder = "Utwórz zamówienie",
    bookmarks = "Zakładki",
    interests = "Zainteresowania",
    aboutBook = "O książce",
    buyNow = "Kup teraz",
    addToCartWithPrice = "Dodaj do koszyka (%s)",
    goToCart = "Przejdź do koszyka",
    payForOrder = "Zapłać za zamówienie",
    share = "Udostępnij",
    books = "Książki",
    searchBooksHint = "Пошук книги за назвою, автором, ISBN …",
    seeAll = "Zobacz wszystko",
    notFound = "Nie znaleziono!",
    bookNotFound = "Nie znaleziono książki!",
    cart = "Wóz",
    preferences = "Preferencje",
    language = "Język"
)

val slovakLocaleStrings = LocalizedStrings(
    and = "a",
    andSpaced = " a ",
    cancel = "Zrušiť",
    pay = "Platiť",
    addToCart = "Pridať do košíka",
    makeOrder = "Urobiť objednávku",
    payWithPrice = "Platiť %s",
    buyWithPrice = "Kúpiť (%s)",
    ordersWithCount = "Objednávky (%d)",
    ratingWithCount = "%.2f (%d)",
    purchaseAllOrders = "Kúpiť všetky",
    quantityLabel = "Množstvo:",
    bookPriceLabel = "Cena knihy:",
    totalPriceLabel = "Celková cena:",
    createOrder = "Vytvoriť objednávku",
    bookmarks = "Záložky",
    interests = "Záujmy",
    aboutBook = "O knihe",
    buyNow = "Kúpiť teraz",
    addToCartWithPrice = "Pridať do košíka (%s)",
    goToCart = "Prejsť do košíka",
    payForOrder = "Zaplatiť za objednávku",
    share = "Zdieľať",
    books = "Knihy",
    searchBooksHint = "Пошук книги за назвою, автором, ISBN …",
    seeAll = "Zobraziť všetky",
    notFound = "Nenájdené!",
    bookNotFound = "Kniha nebola nájdená!",
    cart = "Kôš",
    preferences = "Preferencie",
    language = "Jazyk"
)